version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: server_monitor
      MYSQL_USER: django_user
      MYSQL_PASSWORD: djangopassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - monitor_network

volumes:
  mysql_data:

networks:
  monitor_network: