services:
  db:
    image: mysql:8.0
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: server_monitor
      MYSQL_USER: django_user
      MYSQL_PASSWORD: djangopassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - monitor_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 1s
      retries: 1

  web:
    build: .
    container_name: django_app
    command: sh -c "sleep 10 && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=amo_test_monitoring_app.settings
      - DATABASE_HOST=db
      - DATABASE_NAME=server_monitor
      - DATABASE_USER=django_user
      - DATABASE_PASSWORD=djangopassword
    networks:
      - monitor_network

volumes:
  mysql_data:

networks:
  monitor_network: